[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mirrapy"  # PyPI上の公開名（小文字・ハイフン推奨）
version = "0.1.4"
description = "MirraPyライブラリの説明"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "X-Developer800", email = "shanriyonggou@gmail.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/X-Developer800/MirraPy"